---
title: "IPEDS Financial Metrics"
subtitle: "NCES Data Files"
author: "Jason P. Casey"
date: 2020-04-05
output: html_notebook
params:
  year:
    value: 2016
---

```{r setup}
# libraries
library(knitr)
library(reticulate)
library(lubridate)
library(tidyverse)

# set default document options
knitr::opts_chunk$set(fig.width = 8,
                      fig.asp = 0.618,
                      echo = TRUE,
                      warning = FALSE)
knitr::knit_engines$set(python = reticulate::eng_python)

# set random seed
set.seed(1965)

# access zipped data via net
net_load_zip <- function(file_url, file_name)
{
  #Download data file
  temp <- tempfile()
  
  download.file(file_url,
                temp)
  
  files <- unzip(temp, list = TRUE)

  spec <- files$Name[str_detect(files$Name, "_rv")]

  file_name <- ifelse(length(spec) == 0, file_name, spec)
  
  data <- 
    read_csv(unz(temp, file_name),
             locale = locale(encoding = "latin1"),
             col_types = cols(.default = col_character())) %>%
    rename_all(tolower)
  
  unlink(temp)
  rm(temp)
  
  return(data)
}

# base tibble
years <-
  tibble(`Fiscal Year` = seq(params$year - 7, params$year))
```

# Read Data

## GDP Deflators

```{r}
system.time({
  gdp <-
    read_csv('data/GDPDEF.csv',
             col_types = cols(.default = col_double(),
                              date = col_character())) %>%
    filter(str_sub(date, 1, 3) == '10/') %>%
    mutate(`Fiscal Year` = as.integer(str_sub(date, -2, -1)),
           `Fiscal Year` = ifelse(`Fiscal Year` < 47,
                                  2000 + `Fiscal Year`,
                                  1900 + `Fiscal Year`),
           GDP = gdpdef / 100) %>%
    select(`Fiscal Year`,
           GDP)
})
```

## Financial Responsibility Composite Scores

```{r}
system.time({
  scores <-
    read_csv('data/fin_resp_data.csv',
             col_types = cols(.default = col_character(),
                              composite_year = col_integer(),
                              composite_score = col_double())) %>%
    mutate(`Fiscal Year` = composite_year + 1) %>%
    select(unitid,
           `Fiscal Year`,
           `Composite Score` = composite_score)
})
```

## IPEDS Data

### IC Fields

```{r}
# access data via net
load_ic <- function(year)
{
  url <- str_c('https://nces.ed.gov/ipeds/datacenter/data/IC', year - 1, '.zip')
  name <- str_c('ic', year - 1, '.csv')
  
  net_load_zip(url, name) %>%
    rename_all(tolower)
}

system.time({
  ic_data <-
    years %>%
    mutate(data = map(`Fiscal Year`, load_ic)) %>%
    unnest(cols = data) %>%
    select(unitid, `Fiscal Year`, level5, distnced)
})
```

### HD Fields

```{r}
# access data via net
load_hd <- function(year)
{
  url <- str_c('https://nces.ed.gov/ipeds/datacenter/data/HD', year - 1, '.zip')
  name <- str_c('hd', year - 1, '.csv')
  
  net_load_zip(url, name) %>%
    rename_all(tolower) %>%
    mutate(Control = recode(control,
                            '1' = 'Public',
                            '2' = 'Private',
                            '3' = 'Proprietary',
                            .default = 'Unknown'),
           deathyr = as.integer(deathyr),
           Closed = ifelse(deathyr < 0, 0, 1),
           `Close Year` = ifelse(Closed == 1,
                                 deathyr,
                                 NA),
           `Close Date` = ifelse(closedat == '-2',
                                 NA,
                                 closedat),
           opeflag = as.integer(opeflag),
           obereg = as.integer(obereg)) %>%
    filter(obereg < 9,
           opeflag == 1,
           Control %in% c('Public', 'Private')) %>%
    select(unitid,
           opeid,
           `Institution Name` = instnm,
           City = city,
           State = stabbr,
           Control,
           Closed,
           `Close Year`,
           `Close Date`)
}

system.time({
  institutions <- 
    years %>%
    mutate(data = map(`Fiscal Year`, load_hd)) %>%
    unnest(cols = data)
  
  institutions <-
    institutions %>%
    group_by(unitid) %>%
    summarize(`Fiscal Year` = max(`Fiscal Year`)) %>%
    ungroup() %>%
    inner_join(institutions, by = c('unitid', 'Fiscal Year')) %>%
    inner_join(ic_data, by = c('unitid', 'Fiscal Year')) %>%
    mutate(distnced = ifelse(is.na(distnced), 0, as.integer(distnced)),
           level5 = ifelse(is.na(level5), 0, as.integer(level5))) %>%
    filter(distnced != 1,
           level5 == 1) %>%
    select(-`Fiscal Year`, -distnced, -level5) %>%
    mutate(`Close Date` = as_date(`Close Date`, tz = 'GMT', format='%m/%d/%Y'))
})

# housekeeping
rm(ic_data)
```

### IPEDS F2 Data Files

```{r}
# collapse year
collapse_year <-
  function(year) {
    str_c(str_sub(year - 1, 3 ,4),
          str_sub(year, 3 ,4))
  }

# access data via net
load_fasb <- function(year)
{
  url <- str_c('https://nces.ed.gov/ipeds/datacenter/data/F',
               collapse_year(year),
               '_F2.zip')
  name <- str_c('f',
                collapse_year(year),
                '_f2.csv')
  
  net_load_zip(url, name) %>%
    rename_all(tolower) %>%
    select(-starts_with('x')) %>%
    pivot_longer(cols = 2:ncol(.),
                 names_to = 'field_code',
                 values_to = 'amount') %>%
    replace_na(list(amount = '0')) %>%
    mutate(amount = as.integer(amount))
}

system.time({
  fasb_files <- 
    years %>%
    mutate(accounting_standard = 'FASB',
           data = map(`Fiscal Year`, load_fasb)) %>%
    inner_join(gdp, by = c('Fiscal Year'))
})
```

## Merge Files

```{r}
metrics <-
  fasb_files %>%
  unnest(cols = data) %>%
  filter(field_code %in% c('f2e131', 'f2e091', 'f2h02')) %>%
  pivot_wider(names_from = 'field_code',
              values_from = 'amount') %>%
  replace_na(replace=list(f2e131 = 0, f2e091 = 0, f2h02 = 0)) %>%
  rename(`Accounting Standard` = accounting_standard,
         `Endowment EOY` = f2h02,
         `Total Expenses` = f2e131,
         `Hospital Expenses` = f2e091) %>%
  left_join(scores, by = c('unitid', 'Fiscal Year')) %>%
  inner_join(institutions, ., by = c('unitid')) %>%
  mutate(`Endowment/Expenses` = `Endowment EOY` / (`Total Expenses` - `Hospital Expenses`),
         `Endowment/Expenses (Constant $)` = `Endowment/Expenses` / GDP) %>%
  rename(Unitid = unitid)

rm(institutions, gdp, scores, fasb_files)
```

## Inspect Data

```{r}
metrics %>%
  filter(Control == 'Private',
         is.na(`Endowment/Expenses`)) %>%
  select(Unitid, `Institution Name`, `Fiscal Year`, City, State, `Endowment EOY`, `Total Expenses`)
```

# Plots

```{r}
metrics %>%
  mutate(Closed = factor(Closed)) %>%
  ggplot(aes(x = `Composite Score`, y = `Endowment/Expenses (Constant $)`, color = Closed)) +
    geom_point(alpha = 1/5)
```

# Summary Statistics

## Endowment/Expenses for Private Institutions

```{r}
metrics %>%
  filter(Control == 'Private') %>%
  group_by(`Fiscal Year`) %>%
  summarize(`Mean Endowment/Expenses (Constant $)` = mean(`Endowment/Expenses`, na.rm = TRUE)) %>%
  ungroup()
```

